const D=window.LESSON, $=s=>document.querySelector(s);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
function choosePart(i){$('#part-number').textContent=String(i+1).padStart(2,'0');$('#part-title').textContent=D.parts[i][1];$('#part-description').textContent=D.parts[i][2];document.querySelectorAll('.letter-part').forEach((n,j)=>n.classList.toggle('chosen',i===j));document.querySelectorAll('.part-index button').forEach((n,j)=>{n.classList.toggle('selected',i===j);n.setAttribute('aria-pressed',String(i===j))})}
D.segments.forEach((text,i)=>{const b=el('button','letter-part',text);b.type='button';b.dataset.number=String(i+1).padStart(2,'0');b.setAttribute('aria-label',D.parts[i][1]+': '+text);b.onclick=()=>choosePart(i);$('#letter').append(b);const index=el('button','',String(i+1).padStart(2,'0'));index.title=D.parts[i][1];index.setAttribute('aria-label',D.parts[i][1]);index.onclick=()=>choosePart(i);$('#part-index').append(index)});choosePart(0);
D.notations.forEach(r=>{const n=el('article','notation');n.append(el('h4','',r[0]),el('p','',r[1]),el('small','',r[2]));$('#notations').append(n)});
D.vocabulary.forEach((r,i)=>{const n=el('article','word-card');n.append(el('span','counter',String(i+1).padStart(2,'0')),el('h3','',r[0]),el('p','',r[1]),el('p','combo',r[2].replace('meet standard','meet standards')));$('#vocab-grid').append(n)});
function showView(name){if(!['lesson','vocabulary','practice'].includes(name))name='lesson';document.querySelectorAll('.view').forEach(n=>n.hidden=n.id!==name);document.querySelectorAll('[data-view]').forEach(n=>{n.classList.toggle('active',n.dataset.view===name);n.setAttribute('aria-current',n.dataset.view===name?'page':'false')})}
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));showView(location.hash.slice(1));$('#qr-open').onclick=()=>$('#qr-dialog').showModal();$('.dialog-close').onclick=()=>$('#qr-dialog').close();
let activity='choice';const definitions=D.match.map(r=>r[1]);const matchAnswers=[1,3,5,8,0,7,9,2,4,6];
function renderExercise(){$('#check-answers').hidden=activity==='gap';$('#check-answers').disabled=activity==='gap';const form=$('#exercise');form.replaceChildren();$('#score').textContent='';$('#activity-instruction').textContent=activity==='choice'?'Choose the word that best completes each sentence.':activity==='match'?'Match each word with its definition.':'Complete each sentence. Change the word form when necessary. Word bank: confirm · inspection · thorough · determine · capacity · original · stamp · proceed · meet · collaborate';
const questions=activity==='choice'?D.choice:activity==='match'?D.match:D.gaps;
questions.forEach((r,i)=>{const f=el('fieldset','question');f.append(el('legend','',(i+1)+'. '+(activity==='choice'?r.q:activity==='match'?r[0]:r.q)));const box=el('div','options');
if(activity==='choice'){r.options.forEach((op,j)=>{const label=el('label');const input=el('input');input.type='radio';input.name='q'+i;input.value=String(j);label.append(input,document.createTextNode(op));box.append(label)})}
else if(activity==='match'){const select=el('select');select.name='q'+i;select.setAttribute('aria-label','Definition of '+r[0]);select.append(new Option('Choose a definition…',''));definitions.forEach((d,j)=>select.append(new Option(d,String(j))));box.append(select)}
else{const input=el('input');input.type='text';input.name='q'+i;input.autocomplete='off';input.setAttribute('aria-label','Answer for sentence '+(i+1));box.append(input)}
f.append(box,el('p','feedback'));form.append(f)});}
document.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>{activity=b.dataset.activity;document.querySelectorAll('[data-activity]').forEach(n=>n.classList.toggle('selected',n===b));renderExercise()});
$('#exercise').onsubmit=e=>e.preventDefault();
$('#check-answers').onclick=()=>{if(activity==='gap')return;let score=0;const values=new FormData($('#exercise'));document.querySelectorAll('.question').forEach((f,i)=>{let value=String(values.get('q'+i)??'').trim().toLowerCase();const expected=activity==='choice'?String(D.choice[i].answer):String(matchAnswers[i]);const ok=value===expected;if(ok)score++;f.classList.toggle('correct',ok);f.classList.toggle('incorrect',!ok);const answer=activity==='choice'?D.choice[i].options[D.choice[i].answer]:definitions[matchAnswers[i]];f.querySelector('.feedback').textContent=ok?'Correct.':(value?'Try again. ':'Not answered. ')+'Answer: '+answer;});$('#score').textContent=score+' / 10 correct'+(score===10?' — Well done!':' — Review the feedback and try again.');};
$('#reset-answers').onclick=renderExercise;renderExercise();
$('#checkin-form').onsubmit=async e=>{e.preventDefault();const input=$('#student-id'),status=$('#checkin-status'),button=e.target.querySelector('button');const studentId=input.value.trim().toUpperCase();if(!/^[A-Z0-9-]{4,20}$/.test(studentId)){status.textContent='Enter a valid student ID (4–20 letters, numbers or hyphens).';status.className='status error';return}button.disabled=true;status.className='status';status.textContent='Saving your check-in…';try{const res=await fetch(window.COURSE_CONFIG.attendanceUrl+'/api/checkin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId}),signal:AbortSignal.timeout(15000)});const result=await res.json();if(!res.ok||!result.ok)throw Error(result.error||'Check-in could not be saved.');status.className='status success';status.textContent=(result.duplicate?'Already checked in today: ':'Check-in recorded: ')+studentId+' · '+new Date(result.timestamp).toLocaleString('en-GB',{timeZone:'Asia/Taipei'})+' (Taipei)';}catch(err){status.className='status error';status.textContent='Not confirmed. Please try again or contact your teacher. Your ID is still in the box.'}finally{button.disabled=false}};
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'show_letter_part',description:'Show an explanation for one of the 15 business letter parts.',inputSchema:{type:'object',properties:{part:{type:'integer',minimum:1,maximum:15}},required:['part'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({part})=>{if(!Number.isInteger(part)||part<1||part>15)throw Error('part must be 1–15');showView('lesson');choosePart(part-1);return {part,title:D.parts[part-1][1],explanation:D.parts[part-1][2]}}})}catch{}}
